
version: 2

models:
    - name: j_customers
      description: "Customer Model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: j_orders
      description: "Orders Model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: status
            tests:      
              - accepted_values:
                  values:
                    - returned
                    - completed
                    - return_pending
                    - shipped
                    - placed
          - name: user_id
            tests:
              - relationships:
                  to: ref('j_customers')
                  field: id